#!/bin/bash

#updating the system
echo 'updating ...'
apt update
apt upgrade -y
apt autoremove -y 
echo 'installing unzip ...'
apt install unzip
echo done
clear
echo 'installing PCHAIN'
cd ~
wget https://github.com/pchain-org/pchain/releases/download/pre-release/pchain_init_dirs.zip
unzip pchain_init_dirs.zip
mv pchain_init_dirs/pchain .
cd pchain/
find . -name '*.sh' | xargs chmod +x
chmod +x bin/pchain
./bin/pchain -datadir .pchain init .pchain/pchain/eth_genesis.json
./bin/pchain -datadir .pchainDevAccount init_eth_genesis "{10000000000000000000000000000000000, 100}"
cp .pchainDevAccount/pchain/priv_validator.json .pchain/pchain
cp .pchainDevAccount/pchain/keystore .pchain/pchain/
./run_pchain.sh
echo done
