#!/bin/bash

#updating the system
echo 'updating ...'
sleep 2
apt update
apt upgrade -y
apt autoremove -y 
clear
echo 'installing unzip ...'
sleep 2
apt install unzip
clear
echo done
sleep 2
echo 'installing PCHAIN...'
sleep 2
cd ~
echo 'download...'
wget https://github.com/pchain-org/pchain/releases/download/pre-release/pchain_init_dirs.zip
echo 'install and start...'
sleep 2
unzip pchain_init_dirs.zip
mv pchain_init_dirs/pchain .
cd pchain/
find . -name '*.sh' | xargs chmod +x
chmod +x bin/pchain
./bin/pchain -datadir .pchain init .pchain/pchain/eth_genesis.json
./bin/pchain -datadir .pchainDevAccount init_eth_genesis "{10000000000000000000000000000000000, 100}"
cp .pchainDevAccount/pchain/priv_validator.json .pchain/pchain
cp -r .pchainDevAccount/pchain/keystore .pchain/pchain/
./run_pchain.sh
